### ISSUE TITLE
Seeding Database

### ISSUE THREAD

**Issue by cyrus-shahrivar** [shishkina/q_cards#2]
@amcooper @jasonseminara Node is saying that each document/record needs an _id before saving, but we want it to generate automatically.  I've tried googling it and looking at the docs and can't find a solution.

---

node seed.js
connection successful2 <-- the company collection does save
[Error: document must have an _id before saving]  <-- the user collections does not

**Comment by jasonseminara** [comment]
Sat with team. Inserting an array of objects into Mongoose requires different syntax than inserting only one: http://stackoverflow.com/questions/19701154/mongoose-whats-the-differences-between-model-create-and-collection-insert
